#cerad_user__homepage:
#    path:     /
#   defaults: { _controller: CeradAppBundle:Index:index }
        
cerad_user__oauth__redirect:
    pattern: /oauth/callback
    defaults:
        _controller: CeradUserBundle:OAuth:callback
        
cerad_user__oauth_authorize:
    pattern: /oauth/authorize/{providerName}
    defaults:
        _controller: CeradUserBundle:OAuth:authorize
